version: '3.8'
services:
  s-user-staging:
    image: mohammadnowresideh1997/s-user-staging
    env_file:
      - /root/config/s-user-staging.env.txt
    container_name: s-user-staging
    restart: always
    ports:
      - 3002:3002
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
