version: '3.8'
services:
  s-user-staging:
    image: ${DOCKER_USERNAME}/s-user-staging
    env_file:
      - /root/config/s-user-staging.env.txt
    container_name: s-user-staging
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - services_app-network
    volumes:
      - /root/services/firebase/firebase-bank-system.json:/usr/src/app/firebase-bank-system.json
      - /root/services/firebase/firebase-bank-system.json:/usr/src/app/dist/firebase-bank-system.json

networks:
  services_app-network:
    external: true
