FROM --platform=linux/amd64 node:18.10.0-alpine

WORKDIR /usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json

RUN npm install --force

COPY . .

RUN npm run build

EXPOSE 4002

CMD [ "npm", "run", "start:prod" ]